# analysis_data_schema.py
# TypedDict schema for the analysis_data dict that flows through the pipeline.
#
# analysis_data is created by PeakClassifier.classify_peaks() and progressively
# populated by each pass. All keys are optional (total=False) because the dict is
# built incrementally and some keys only exist when optional pipeline stages run.
#
# Usage: annotate your local variable to get IDE autocomplete and type checking:
#   analysis_data: AnalysisData = classifier.classify_peaks()[2]
#
# When adding a new output: add its key here first, then write to it in the pass
# that produces it. Removing a key: grep for it across all files before deleting.

from __future__ import annotations
from typing import Any, Optional, TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    import pandas as pd

# ---------------------------------------------------------------------------
# Helpers for keys generated by _compute_and_store_measured_phase_curves.
# Called with three prefixes:
#   "pass3_measured_phase_before_repair" — after initial state build, before noise/gap repair
#   "pass3_measured_phase_for_gap_insert" — intermediate snapshot used by gap-insert logic
#   "pass3_measured_phase_final"          — final state after all corrections
#
# Each call stores 8 keys:
#   {prefix}_systole_t       sparse S1→S2 event times (seconds, np.ndarray)
#   {prefix}_systole_dur     sparse S1→S2 durations (seconds, np.ndarray)
#   {prefix}_diastole_t      sparse S2→S1 event times (seconds, np.ndarray)
#   {prefix}_diastole_dur    sparse S2→S1 durations (seconds, np.ndarray)
#   {prefix}_systole_times   dense rasterized systole times (np.ndarray)
#   {prefix}_systole         dense rasterized systole durations (np.ndarray)
#   {prefix}_diastole_times  dense rasterized diastole times (np.ndarray)
#   {prefix}_diastole        dense rasterized diastole durations (np.ndarray)
# ---------------------------------------------------------------------------


try:
    from typing import TypedDict
except ImportError:
    from typing_extensions import TypedDict  # type: ignore[assignment]


class AnalysisData(TypedDict, total=False):
    # =========================================================================
    # Preprocessing — set by pipeline.py before Pass 1 and Pass 2
    # =========================================================================

    bandpass_envelope: np.ndarray
    """Main PCG signal envelope: bandpass-filtered + Hilbert abs, shape (n_samples,)."""

    inverse_band_envelope: Optional[np.ndarray]
    """HF (noise-band) envelope used for noise-segment detection. None if disabled."""

    noise_removed_envelope: Optional[np.ndarray]
    """Envelope with HF noise regions zeroed/attenuated. None if not computed."""

    noise_event_segments: list
    """HF noise time regions: list of (start_sec, end_sec) float tuples."""

    # =========================================================================
    # Pass 2 — set by classifier.py (PeakClassifier.classify_peaks)
    # =========================================================================

    dynamic_noise_floor_series: "pd.Series"
    """Rolling quantile noise floor; index is sample index, values are floor amplitudes."""

    trough_indices: np.ndarray
    """Sample indices of detected inter-peak troughs (int64 array)."""

    deviation_series: np.ndarray
    """Smoothed amplitude deviation series, same length as bandpass_envelope."""

    peak_classifications: dict
    """Per-peak classification result dict. Keys are sample indices (int). Values are
    dicts with keys: label (str), confidence (float), s1_prominence, s2_prominence, etc."""

    s1_s2_pairs: list
    """Accepted S1→S2 (systole) pairs from Pass 2. Each element is a named-tuple or dict
    with s1_idx, s2_idx, confidence, interval_sec, and related diagnostics."""

    pass2_lt_bpm_times: np.ndarray
    """Time grid (seconds) for the long-term BPM estimate from Pass 2."""

    pass2_lt_bpm: np.ndarray
    """Long-term BPM values at pass2_lt_bpm_times. Same length."""

    # =========================================================================
    # Pass 2 → pipeline — set by pipeline.py after classify_peaks
    # =========================================================================

    fft_separation: Optional[Any]
    """S1 vs S2 frequency separation vector (from fft_profiles.compute_frequency_separation).
    None when FFT profiles are disabled or when too few peaks exist."""

    bpm_failure_report: dict
    """Algorithm-agnostic post-hoc plausibility gate result (hrv.detect_bpm_failure), mirrored
    here from metrics_after_pass3 for callers that only see analysis_data (debug_helpers,
    benchmarking). Shape: {"failed": bool, "reasons": [str, ...], "metrics": {...}}."""

    algorithm_used: str
    """Which algorithm actually produced this result: "native" or "springer". Set by
    pipeline._run_algorithm_pass; may differ from the "use_springer_algorithm" param if
    auto_switch_algorithm retried with the other algorithm."""

    algorithm_switch_reason: Optional[str]
    """None unless auto_switch_algorithm retried and switched away from the primary
    algorithm; otherwise a human-readable reason string for the report/plot annotation."""

    # =========================================================================
    # Pass 3 core outputs — set by correction.run_pass3_correction
    # =========================================================================

    pass3_state_labels: np.ndarray
    """Per-sample state label array (int8), shape (n_samples,).
    Decode with pass3_state_labels_encoding: e.g. 1=S1, 2=systole, 3=S2, 4=diastole, 0=unknown."""

    pass3_state_labels_encoding: dict
    """Maps state name (str) → int label used in pass3_state_labels. E.g. {"s1": 1, ...}."""

    pass3_state_boundaries: list
    """State boundary tuples after all Pass 3 corrections. Each tuple describes one
    labeled segment: (state_name, start_sec, end_sec, metadata_dict)."""

    pass3_state_boundaries_before: list
    """State boundaries before noise/gap repair — preserved for before/after overlay in plots."""

    pass3_corrections: list
    """Records of each correction applied in Pass 3 (for debug overlay in plots)."""

    pass3_cycle_diagnostics: list
    """Per-cycle timing diagnostics (one entry per detected cardiac cycle)."""

    pass3_spectral_context: None
    """Placeholder for future spectral context. Always None currently."""

    pass3_bpm_prior_times: np.ndarray
    """Time grid (seconds) for the BPM prior used inside Pass 3."""

    pass3_bpm_prior: np.ndarray
    """BPM prior values at pass3_bpm_prior_times."""

    # =========================================================================
    # Pass 3 debug windows — set by correction.run_pass3_correction
    # =========================================================================

    pass3_noise_unreliable_windows_samples: list
    """Noise-affected windows as list of (start_sample, end_sample) int pairs."""

    pass3_large_gap_windows_samples: list
    """Large-gap windows as list of (start_sample, end_sample) int pairs."""

    pass3_gap_quiet_windows_samples: list
    """Quiet sub-windows within large gaps (for debug overlay)."""

    pass3_large_gap_recovered_peaks_insensitive: list
    """Sample indices of peaks recovered inside gap windows by the conservative detector."""

    pass3_large_gap_recovered_peaks_sensitive: list
    """Sample indices of peaks recovered by the sensitive (low-threshold) detector."""

    pass3_gap_decision_peaks_sensitive: list
    """Sample indices of the sensitive peaks find_gap_windows used to decide each
    gap/insert. Detected over the source segment; can differ from the recovered
    sets above (re-detected over the trimmed window). Plotted as debug evidence."""

    # =========================================================================
    # Pass 3 measured phase curves — "before_repair" snapshot
    # Set by _compute_and_store_measured_phase_curves(key_prefix="pass3_measured_phase_before_repair")
    # =========================================================================

    pass3_measured_phase_before_repair_systole_t: np.ndarray
    pass3_measured_phase_before_repair_systole_dur: np.ndarray
    pass3_measured_phase_before_repair_diastole_t: np.ndarray
    pass3_measured_phase_before_repair_diastole_dur: np.ndarray
    pass3_measured_phase_before_repair_systole_times: np.ndarray
    pass3_measured_phase_before_repair_systole: np.ndarray
    pass3_measured_phase_before_repair_diastole_times: np.ndarray
    pass3_measured_phase_before_repair_diastole: np.ndarray

    # =========================================================================
    # Pass 3 measured phase curves — "for_gap_insert" intermediate snapshot
    # Set by _compute_and_store_measured_phase_curves(key_prefix="pass3_measured_phase_for_gap_insert")
    # =========================================================================

    pass3_measured_phase_for_gap_insert_systole_t: np.ndarray
    pass3_measured_phase_for_gap_insert_systole_dur: np.ndarray
    pass3_measured_phase_for_gap_insert_diastole_t: np.ndarray
    pass3_measured_phase_for_gap_insert_diastole_dur: np.ndarray
    pass3_measured_phase_for_gap_insert_systole_times: np.ndarray
    pass3_measured_phase_for_gap_insert_systole: np.ndarray
    pass3_measured_phase_for_gap_insert_diastole_times: np.ndarray
    pass3_measured_phase_for_gap_insert_diastole: np.ndarray

    # =========================================================================
    # Pass 3 measured phase curves — "final" snapshot (primary output)
    # Set by _compute_and_store_measured_phase_curves(key_prefix="pass3_measured_phase_final")
    # =========================================================================

    pass3_measured_phase_final_systole_t: np.ndarray
    """Sparse systole event times (seconds) after all corrections."""

    pass3_measured_phase_final_systole_dur: np.ndarray
    """Sparse S1→S2 durations (seconds) after all corrections."""

    pass3_measured_phase_final_diastole_t: np.ndarray
    """Sparse diastole event times (seconds) after all corrections."""

    pass3_measured_phase_final_diastole_dur: np.ndarray
    """Sparse S2→S1 durations (seconds) after all corrections."""

    pass3_measured_phase_final_systole_times: np.ndarray
    """Dense rasterized systole time grid."""

    pass3_measured_phase_final_systole: np.ndarray
    """Dense rasterized systole durations (seconds)."""

    pass3_measured_phase_final_diastole_times: np.ndarray
    """Dense rasterized diastole time grid."""

    pass3_measured_phase_final_diastole: np.ndarray
    """Dense rasterized diastole durations (seconds)."""

    # =========================================================================
    # Pass 3 convenience aliases — set at end of run_pass3_correction
    # These mirror the pass3_measured_phase_final_* values under shorter names.
    # =========================================================================

    pass3_measured_systole_t: np.ndarray
    """Alias for pass3_measured_phase_final_systole_t."""

    pass3_measured_systole_dur: np.ndarray
    """Alias for pass3_measured_phase_final_systole_dur."""

    pass3_measured_diastole_t: np.ndarray
    """Alias for pass3_measured_phase_final_diastole_t."""

    pass3_measured_diastole_dur: np.ndarray
    """Alias for pass3_measured_phase_final_diastole_dur."""

    pass3_measured_systole_times: np.ndarray
    """Alias for pass3_measured_phase_final_systole_times (rasterized)."""

    pass3_measured_systole: np.ndarray
    """Alias for pass3_measured_phase_final_systole (rasterized durations)."""

    pass3_measured_diastole_times: np.ndarray
    """Alias for pass3_measured_phase_final_diastole_times (rasterized)."""

    pass3_measured_diastole: np.ndarray
    """Alias for pass3_measured_phase_final_diastole (rasterized durations)."""

    # =========================================================================
    # Pass 4 (Viterbi) — set by viterbi.run_viterbi_pass
    # =========================================================================

    pass3_emissions: np.ndarray
    """Emission probability matrix (shape T×3) feeding the Viterbi decoder.
    See pass3 archived logic.md for the generation code (currently disabled)."""

    pass4_state_sequence: np.ndarray
    """Viterbi-decoded state label sequence (int32, shape n_samples)."""

    pass4_s1_peaks: np.ndarray
    """S1 peak sample indices derived from the Viterbi state sequence (int64)."""
